version: '2'
services:
    hehe-app:
        image: hehe
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hehe-postgresql:5432/hehe
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hehe-postgresql:
        extends:
            file: postgresql.yml
            service: hehe-postgresql
